question_data = [
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
        "question": "French is an official language in Canada.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
        "question": "It is automatically considered entrapment in the United States if the police sell you illegal substances without revealing themselves.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
        "question": "The Sun rises from the North.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
        "question": "You can legally drink alcohol while driving in Mississippi.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
        "question": "On average, at least 1 person is killed by a drunk driver in the United States every hour.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
        "question": "In 2010, Twitter and the United States Library of Congress partnered together to archive every tweet by American citizens.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
        "question": "When you cry in space, your tears stick to your face.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
        "question": "Dihydrogen Monoxide was banned due to health risks after being discovered in 1983 inside swimming pools and drinking water.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
        "question": "A pasodoble is a type of Italian pasta sauce.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
        "question": "Slovakia is a member of European Union-", "correct_answer": "True", "incorrect_answers": ["False"]}
]
